### ISSUE TITLE
Device name wildcard

### ISSUE THREAD

**Issue by lrybak** [dannybloe/dzVents#1]
First of all, I found your scripts extremely usefull. Well done

I have a question. Is it possible to trigger script based on device name wildcard, ex:
on = {
'PIR *'
}

I'd like to reuse my script for set of PIR devices, how can I achieve this?

**Comment by dannybloe** [comment]
Sounds like a plan. I guess I will use the Lua regular expression syntax for this.

**Comment by dannybloe** [comment]
Please test this in 0.9.8. It should work like that now.
