### ISSUE TITLE
Setpoint causes 10 sec warning

### ISSUE THREAD

**Issue by MarcusKlerks** [dannybloe/dzVents#10]
I use a virtual setpoint device for setting a required temperature. A known 'feature' of such device is that you have to update it regularly in order to avoid the 'red bar'. dzVents has a means to set the setpoint by using:
  domoticz.devices[setpoint_device].update(0, setpoint_value)
Using this another Domoticz 'feature' manifests itself: you get a lua running for more than 10 sec warning. This is a known problem but never got repaired but luckily there is a workaround by using json:
  domoticz.openURL('http://ip:port/json.htm?type=command&param=udevice&idx=' ..    idx .. '&nvalue=0&svalue=' .. setpoint_value)
This works for me but it would be nice if it could fit in dzEvents code.

**Comment by dannybloe** [comment]
So how about I create a updateSetPoint(value) method that does just that? I could make a setting in the dzVents_settings to tell it to use openURL instead of update().

**Comment by MarcusKlerks** [comment]
That's exactly what I was hoping for...

**Comment by dannybloe** [comment]
Ok, I added the function. It works only for dummy thermostat devices:

`  updateSetPoint(setPoint): Function. Update set point for dummy thermostat devices. This will use the openURL command to prevent the script from timing out.`

Give it a try.

**Comment by MarcusKlerks** [comment]
Almost :)
In Devices.lua you check on 
  self.hardwareName == 'Dummy' 
which should be 
  self.hardwareName == **'DummyHW'**
with that it works like a charm, thanks.

**Comment by MarcusKlerks** [comment]
Correction, it doesn't work due to the extra 'if (setPoint ~= self.setPoint)' that kills the whole idea of preventing the widget bar to turn red due to missing updates. Is it the rest of your code that would create a loop since when I invoke json directly or thru openURL it doesn't cause any problem?

**Comment by dannybloe** [comment]
You are absolutely right. My bad. 
The hardwareName is user-defined btw. I changed the code so it checks for the hardware value which is always 15 (I hope) for dummy devices.

**Comment by MarcusKlerks** [comment]
Works (really) like a charm now. I forgot about the hardware name, long time ago since I created that hardware but hardwaretype or harwaretypevalue seems the right way to check.
Thank for the solution.
