### ISSUE TITLE
update a dummy device impossible

### ISSUE THREAD

**Issue by Merangle** [dannybloe/dzVents#11]
Hello 
I'm moving my Lua scripts to dzVents. It works well, .....but I've problem with a dummy devices. 

I try to update a dummy switch defined as General Current
 ("HardwareName" : "Ampere",
  "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15)
with this command  = domoticz.devices['Prises'].update(0,PrisesWatt)

i get this error message 
An error occured when calling event handler Compteur
2016-05-20 23:58:56.711 LUA: /usr/local/domoticz/var/scripts/lua/scripts/Compteur.lua:64: attempt to index field 'Prises' (a nil value)
2016-05-20 23:58:56.711 LUA: .....................................................

this command 	Lecture = domoticz.devices['Conges'].name works well where 'conges' is a dummy switch device
this one domoticz.devices['Prises'].name doesn(t work neither ....

this command domoticz.devices['Chauffage'].update(0,ChauffageWatt..';'..ChauffageCumul) where Chauffage is a dummy defined, General KWh doesn't work neither....

Is there an issue with this type of dummy devices ? 
Any help would be appreciated ?

**Comment by dannybloe** [comment]
Hi there,  thanks for reporting. Have you tried it with the dev branch?

**Comment by Merangle** [comment]
Hello 

I was on the stable branch. 
After a reboot, the dummy device was recognized and then updated. 

Sorry to have bother you, the problem was not related to dzVents. 

I continue to 'translate' my programs and create some new one.
Thanks for the job (great one !!!!)
