### ISSUE TITLE
Get the description in device map

### ISSUE THREAD

**Issue by octera** [dannybloe/dzVents#12]
Having description in device map may be usefull.
For exemple, the example script checking device node can use description instead of the value map define at the begining.
The device to check, should contains in description, for exemple : 
```
CheckDeadNode : 600 minutes
PIR
```

In this case, this device will alert if no signal for more than 600 minutes, but the security plugin can also use the PIR line to know that device should raise an alarm instead of using device name

**Comment by dannybloe** [comment]
I'm afraid I cannot follow you. Could you elaborate a bit?

**Comment by octera** [comment]
In your example script check dead devices.lua
You have at the begging 
```
local devicesToCheck = {
	{ ['name'] = 'Sensor1', ['threshold'] = 30 },
	{ ['name'] = 'Sensor2', ['threshold'] = 30 },
	{ ['name'] = 'Bathroom temperature', ['threshold'] = 20 }
}
```

Instead of using/editing this var, we can use/edit description field of the device to tell the treshold.
In the description of the Sensor1 we could have "CheckDeadThreshold=30min"

The dead devices.lua will iterate through device, find which contains CheckDeadThreshold in description field, and parse the delay.

With this approch, the responsability to be check is on the device and not the script.

Moreover, the alarm script, can look into description field instead of name to know PIR sensor.

Hope It was more clear

**Comment by dannybloe** [comment]
Sure that's possible. This was just an example. Of course there are many ways you could do this. Feel free to submit another example using this method. We could add it to the list of examples.

**Comment by octera** [comment]
In order to create example, the device object has to contains the description.
Could you add it or give me advice to do it (and I will do a PR). At this moment, I don't understand how you populate de device object to do this by myself

**Comment by dannybloe** [comment]
ah, ok. I get what you mean. There was no description indeed. I just added it in the dev branch so you can try it out. You do need to have http-fetching enabled in the settings as the description is not passed from Domoticz to the scripts.
