### ISSUE TITLE
Error when using a device just created 

### ISSUE THREAD

**Issue by Merangle** [dannybloe/dzVents#13]
Hello 

Each time I read/update a device just created in domoticz, i get an error.
I have to restart domoticz, and then it works well. (it looks like the device is recognized by dzVents after the reboot). 

Is there anything I do wrong ?
Something else I have to do?

**Comment by dannybloe** [comment]
Can you show me the error messages from the logs? What kind of device is it that you create?

**Comment by Merangle** [comment]
I have to prepare a new scenario to provide you some informations.
I will do it in the next few days.
thanks

2016-05-31 20:06 GMT+02:00 Danny Bloemendaal <notifications@github.com>:

**Comment by Merangle** [comment]
Hello
I've just created a new device and did not stop and start domoticz.
The device is updated with this program
:
domoticz.devices['Duree '..Piece.."2"].update(0,Duree)

and I get this error message (whatever I do read and/or update the device)

2016-06-05 10:05:15.160 LUA: An error occured when calling event handler
Thermostat
2016-06-05 10:05:15.160 LUA:
/usr/local/domoticz/var/scripts/lua/scripts/Thermostat.lua:113: attempt to
index field '?' (a nil value)
2016-06-05 10:05:15.163 EventSystem: Script event triggered:
/usr/local/domoticz/var/scripts/lua/script_time_main.lua

As soon as I restart Dz, I can read/update the newly created device.

I'm using a Synology DS212.

Thanks for your help.


2016-05-31 20:06 GMT+02:00 Danny Bloemendaal <notifications@github.com>:

**Comment by dannybloe** [comment]
Can you send me the entire script?

**Comment by Merangle** [comment]
​Here it is

see line 113
​

2016-06-05 11:21 GMT+02:00 Danny Bloemendaal <notifications@github.com>:

**Comment by dannybloe** [comment]
Ehm.. I don't seen anything ...Did you attach anything?

**Comment by Merangle** [comment]
Hello
Once again with a .txt format file

The problem seems to be quite the same for other programs.
I  need to stop/restart domoticz to have this newly created devices
recognized ( the error message is related to a nil value).

Remember I'm using domoticz witha a Synology DS212.

Except this issue, it's working well. Thanks for the job you did.
Regards.



2016-06-05 19:56 GMT+02:00 Danny Bloemendaal <notifications@github.com>:

> Ehm.. I don't seen anything ...Did you attach anything?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dannybloe/dzVents/issues/13#issuecomment-223827233>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASmDari-xh3IPMUKaIkYIWZjnU7yN10Xks5qIw3fgaJpZM4IpDDy>
> .
>

-- Chargement du fichier des outils
local LuaPath = ";/volume1/@appstore/domoticz/var/scripts/lua/?.lua"
package.path = package.path..LuaPath
Tools = require ("Tools")

------------------------------------------------------
-- Regulation chauffage en mode PID
------------------------------------------------------
local Check = {
	['name1'] = 'Parents',
	['name2'] = 'Clementine',
	['name3'] = 'Camille',
	['name4'] = 'Diane',
	['name5'] = 'Salon',
	['name6'] = 'Cuisine',
	['name7'] = 'SdB'
}

return {
	active = true,
	on = {
		['timer'] = 'every minute'
--		timer = function(domoticz)
--		return domoticz.variables['Cycle']
	},

execute = function(domoticz)

	local Prefixe = "Thermostat ==> "
	local Debug = domoticz.variables['Debug Thermostat'].value
	local Pushover = domoticz.variables['Pushover Thermostat'].value

	local SondeTimeOut = 30 -- Si derniere lecture > TimeOut ==> probleme de sonde donc arret radiateur
	local TempOffset = 3	-- Si temperature > Consigne + TempOffset ==> probleme de caclcul donc arret rediateur 

-----------------------------
---- Programme principal ----
-----------------------------
 -- Recuperation de la temperature exterieure
	local TempExt = tonumber(string.format("%.1f",domoticz.devices['Boulogne'].temperature))
	local Saison = domoticz.variables['Saison'].value
-- 	le timer doit etre superieur a Cycle pour eviter de relancer	
	local Cycle = tonumber(domoticz.variables['Cycle'].value) -- duree du Cycle en minutes
	local CycleIn = 'Off' -- On n'est pas dans un cycle
--	Si on est dans le cycle pas de changement des radiateurs
	local Previous = domoticz.variables['Cycle Time'].value
	local DureeCycle = tonumber(string.format("%0.f",os.difftime(os.time(),Previous)/60))
--	if (Debug == 'On') then Tools.Debug(Prefixe.."DureeCycle "..DureeCycle) end
	if (DureeCycle < Cycle) then CycleIn = 'On' end
	Tools.Message(Prefixe.."Cycle de Chauffage = "..DureeCycle)
	
	for i, Piece in pairs(Check) do

--	Initialisation des variables locales
		local Alerte = 'Off' -- pas d'alerte
		local Raison = '' -- pas d'alerte
		
-- 	Recuperation des parametre de la piece	
		local KInt = tonumber(domoticz.variables['Kint '..Piece].value)
		local KExt = tonumber(domoticz.variables['Kext '..Piece].value)
		local Consigne = tonumber(string.format("%.1f",domoticz.devices['Consigne '..Piece].setPoint))
		local TempInt = tonumber(string.format("%.1f",domoticz.devices['Temperature '..Piece].temperature))
		local Sens = domoticz.variables['Sens '..Piece].value

-- 	Controle de la sonde
		local Lecture = tonumber(domoticz.devices['Temperature '..Piece].lastUpdate.minutesAgo)
--		if (Debug == 'On') then Tools.Debug(Prefixe.."Piece = "..Piece.." Lecture "..Lecture) end
		if (Lecture > tonumber(SondeTimeOut)) then Alerte = 'On' Raison = "Sonde" goto Alerte end   

-- 	Controle de la temperature
--		if (TempInt > Consigne + TempOffset) then Alerte = 'On' Raison = "Offset" goto Alerte end
		
--	Calcul des ecarts interne et externe
		EcartInt = Consigne - TempInt
		EcartExt = Consigne - TempExt
	
--	Calcul de la commande de chauffage bornee entre 0 et 100
		CmdChauff = math.min(math.max( (KInt*EcartInt + KExt*EcartExt),0),100)

--	Calcul de la duree de chauffage
		Duree = tonumber(string.format("%.0f",tostring(CmdChauff * Cycle / 100)))
		Tools.Message(Prefixe.."Piece= "..Piece.." Consigne= "..Consigne.." Ext= "..TempExt.." Int= "..TempInt.." %= "..CmdChauff.." Duree= "..Duree.." Int= "..EcartInt.." Ext= "..EcartExt.." KInt= "..KInt.." KExt= "..KExt)

-- 	Si pendant le cycle on ne change rien
		if (CycleIn == 'On') then goto Alerte end
		
--	Envoi de la commande au radiateur
::Action::
		if (Sens == "Normal") then
			if (Duree ~= 0) then 
				domoticz.devices['H '..Piece].switchOn().for_min(Duree)
			else 
				domoticz.devices['H '..Piece].switchOff()
			end
		else 
			if (Duree ~= 0) then 
				domoticz.devices['H '..Piece].switchOff().for_min(Duree)
				if (Piece == 'Salon' ) then domoticz.devices['H Salon Bis'].switchOff().for_min(Duree) end
			else 
				domoticz.devices['H '..Piece].switchOn()
				if (Piece == 'Salon' ) then domoticz.devices['H Salon Bis'].switchOn() end
			end 
		end

--	Envoi d'information
		if (Pushover == 'On') then
			if (Duree ~= 0) then domoticz.notify("Thermostat "..Piece,"Int = "..EcartInt.." Ext = "..EcartExt.." Duree = "..Duree,PRIORITY_NORMAL,SOUND_NONE) end
		end

--	Affichage des parametres
		domoticz.devices['Interne '..Piece].updateTemperature(EcartInt)
		domoticz.devices['Externe '..Piece].updateTemperature(EcartExt)
		domoticz.devices['Duree '..Piece].update(0,Duree)
		
-- 	Gestion des alertes
::Alerte::
		if (Alerte == 'On' and Saison ~= 'summer') then 
			if (Sens == "Normal") then
				domoticz.devices['H '..Piece].switchOff()
			else
				domoticz.devices['H '..Piece].switchOn()
				if (Piece == 'Salon' ) then domoticz.devices['H Salon Bis'].switchOn() end
			end
			Tools.Alerte (Prefixe.."Piece "..Piece.." Probleme Thermostat "..Raison)
			if (Pushover == "On") then domoticz.notify("Thermostat "..Piece,"Probleme Thermostat "..Raison.." Temp "..TempInt,PRIORITY_NORMAL,SOUND_NONE) end
		end
	
-- On note le temps du nouveau cycle 
	if (CycleIn == 'Off') then domoticz.variables['Cycle Time'].set(os.time()) end

	end
end
}

**Comment by svde** [comment]
I've seen the same behavior. Needed to restart domoticz to get dzventz to "see" all the devices.

**Comment by dannybloe** [comment]
I will close this issue as in the upcoming release there's a complete rewrite of everything. See if this still occurs then.
