### ISSUE TITLE
Time delay parametrized

### ISSUE THREAD

**Issue by Merangle** [dannybloe/dzVents#14]
In the 'on' section at the beginning you can use the timer option with several sub-options (minute, xx minutes, ...) 
Is it possible to have the delay time ('xx' as a sub-option) parametrized (for example, by reading a user-variable in domoticz) ?

Thanks for the job done with dzVents

**Comment by dannybloe** [comment]
Something like this?

```
return {
    ...
    timer=function(domoticz)
        return domoticz.variables['myvar']
    end,
    ....
}
```

**Comment by Merangle** [comment]
yes :)

i better understand how to use the function ...

thanks


2016-05-31 20:05 GMT+02:00 Danny Bloemendaal <notifications@github.com>:

**Comment by Merangle** [comment]
Hello 
This issue is labelled "enhancement". 
Does it mean, that you intend to implement this  enhancement ? 
Is it available ? 
If yes since which version ?
If no, do you have an idea in which future version it will implemented ? and when ?

Thanks a lot !
Bye

**Comment by dannybloe** [comment]
In the mean time you can do this:
```
return {
	active = function(domoticz)
		...
	end, 

	on = 'timer',
	execute = function(..) ... end
}
```
The timer makes sure the script is triggered every minute and the active function can override the execution. If the function returns false it won't execute.

**Comment by dannybloe** [comment]
In the next major release (integration with domoticz) this is implemented:

```
return {
    on = {
         timer = {
               '16:50-19:20', 
               function(domoticz)
                      return domoticz.variables['myVar'] == 1
               end
         }
    }
}
```
Note that the resolution is always one minute.
