### ISSUE TITLE
Possibility to create device triggers with time contraints

### ISSUE THREAD

**Issue by dannybloe** [dannybloe/dzVents#16]
```
    on = {
        'myDevice' = { 'at 13:*', 'at 14:*', 'on sat, sun, mon'}
    }

```

which will only trigger the script when myDevice changes on saturday, sunday, monday between 13:00-15:00 hours.

**Comment by dannybloe** [comment]
Done

**Comment by domoticz410** [comment]
Are all these enhancements and changes reflected in the documentation?  I'm a newbee to dzvents and Imrwally like it, but making updates that only limited people know about make no sense.  Please update readme.md file as it hasn't changed for 8 months !

**Comment by dannybloe** [comment]
Of course this will be updated in the docs. First finalizing the code. The new stuff is not in this repository. The new stuff will be part of Domoticz and then this repo will be closed. And the docs will be moved to the domoticz wiki.

**Comment by domoticz410** [comment]
Hi Danny,

Anhow, reaaaaaaaaaaally great that you bring dzvents.

So dzvents way of working will "jusr" be part of Domoticz new release?
When is the release date?

Rgds

**Comment by dannybloe** [comment]
We are almost done. Hopefully it will be in the beta in the coming couple of weeks.

**Comment by domoticz410** [comment]
As new Domoticz release to download or dzvents standalone?

**Comment by dannybloe** [comment]
I don't know when there is a new Domoticz release but it will be in the beta first and not as standalone but as part of Domoticz.
