### ISSUE TITLE
time triggers using ranges

### ISSUE THREAD

**Issue by dannybloe** [dannybloe/dzVents#17]
```
    on = {
        'every minute between 14:15 and 15:25 on sat, sun'
    }

```

**Comment by jimphelps** [comment]
Hi Danny,
This could be a good workaround for beat skip problem. I had many problems with that.
An idea to make something like this while waiting?
Thanks.

**Comment by dannybloe** [comment]
Added this option in the next release (domoticz integration).

`'at 16:45-21:22 on mon, tue'`

Also added:

`'at nighttime', 'at daytime' and function(time) ... end`

And of course you can do crazy stuff:
`at nighttime at 21:32-05:44 every 5 minutes on sat, sun`
