### ISSUE TITLE
Device usage

### ISSUE THREAD

**Issue by DomotRikz** [dannybloe/dzVents#2]
First of all, great script!

I am trying to find a way to read out the usage (Watts) of my devices. Could you please extend the device object with that?

Thank you!

**Comment by dannybloe** [comment]
As far as I know, if a device like a dimmer reports the wattage then this is a separate device with a different id and a different name. You can see in the device list in Domoticz which one it is.

**Comment by dannybloe** [comment]
Let me know if there's still a problem. Closing the ticket now.
