### ISSUE TITLE
attribute level from Alert sensor

### ISSUE THREAD

**Issue by tomasss1024** [dannybloe/dzVents#20]
Hello,
please add attribute level from Alert sensor in Domoticz.lua(453):

```
                                        device.addAttribute('signalLevel', httpDevice.SignalLevel)
+                                        device.addAttribute('level', httpDevice.Level)

```

thanks for dzVents
Tomas

**Comment by dannybloe** [comment]
That would overwrite the real-time level data for dimmers. Can you paste the exact device entry in devices.lua for this kind of hardware?

**Comment by tomasss1024** [comment]
It's only Alert and I need Alert level value:
```
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "OK",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Dummy",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "82044",
         "LastUpdate" : "2016-07-12 17:34:04",
         "Level" : 1,
         "Name" : "Current alert 1",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : false,
         "SignalLevel" : "-",
         "SubType" : "Alert",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "Alert",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "45"
      }
   ],
```

**Comment by dannybloe** [comment]
I added support for the level. Can you check this with the dev branch?

**Comment by tomasss1024** [comment]
hello, there is an error in dev branch
`
2016-07-27 11:08:30.629  Hardware Monitor: Fetching data (System sensors)
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
lsof: status error on /home/tomas/domoticz/scripts/lua/dzVents/../devices.lua.tmp: No such file or directory
lsof 4.86
 latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
 latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
 latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
 usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[gG]] [+|-e s]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
[+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
`

**Comment by tomasss1024** [comment]
I replaced only Device.lua and Domoticz.lua and It seams to be OK for "Alert level" and also for "Dimmer switch".
Thanks

**Comment by dannybloe** [comment]
Mmm, that's weird. You do use the http-fetching stuff don't you?

**Comment by tomasss1024** [comment]
yes, http fetch

**Comment by dannybloe** [comment]
I added a check. Seems that I try to access devices.lua.tmp before it was fetched. Should work now in the dev branch.

**Comment by tomasss1024** [comment]
now, it's ok, thanks. Also I change write attribute to /run/user/1000/gvfs
