### ISSUE TITLE
Add support for Windows-based environments

### ISSUE THREAD

**Issue by dhanjel** [dannybloe/dzVents#24]
dzVents really makes Domoticz stand out from the rest of the home automation systems and makes powerful and complex scenarios easy to create.

One disadvantage is that it currently does not support Windows based environments (I am drooling over a LattePanda board and running Windows instead, but I would never consider leaving dzVents behind).

And if support is added for Windows as well, then it perhaps can be merged together with the Domoticz source code.

**Comment by dannybloe** [comment]
This is taken care of in the next release which will be integrated into domoticz.
