### ISSUE TITLE
Add HardwareTypeVal = 68 for Setpoint

### ISSUE THREAD

**Issue by MarcusKlerks** [dannybloe/dzVents#26]
I intend to make an active use of my Nefit Easy thermostat (e.g. decrease setpoint when door to outside is open) but got an error that the setpoint device is not supported. The json for this setpointdevice looks like: `{
         ["AddjMulti"]= 1.0,
         ["AddjMulti2"]= 1.0,
         ["AddjValue"]= 0.0,
         ["AddjValue2"]= 0.0,
         ["BatteryLevel"]= 255,
         ["CustomImage"]= 0,
         ["Data"]= "20.5",
         ["Description"]= "",
         ["Favorite"]= 0,
         ["HardwareID"]= 9,
         ["HardwareName"]= "Nefit Easy",
         ["HardwareType"]= "Nefit Easy HTTP server over LAN interface",
         ["HardwareTypeVal"]= 68,
         ["HaveTimeout"]= false,
         ["ID"]= "0010101",
         ["LastUpdate"]= "2016-10-10 18:29:53",
         ["Name"]= "Nefit | Setpoint",
         ["Notifications"]= "false",
         ["PlanID"]= "0",
         ["PlanIDs"]= { 0 },
         ["Protected"]= false,
         ["SetPoint"]= "20.5",
         ["ShowNotifications"]= true,
         ["SignalLevel"]= "-",
         ["SubType"]= "SetPoint",
         ["Timers"]= "false",
         ["Type"]= "Thermostat",
         ["TypeImg"]= "override_mini",
         ["Unit"]= 1,
         ["Used"]= 1,
         ["XOffset"]= "0",
         ["YOffset"]= "0",
         ["idx"]= "105"
      }`
Looking at the code in Device.lua I found that it check on HardwareTypeVal which doesn't include the value (68) for the Nefit Easy thermostat.
Adding the value in line 294 like:
`if ((self.hardwareTypeVal == 15 or self.hardwareTypeVal == 20 or self.hardwareTypeVal == 68) and self.deviceSubType == 'SetPoint') then`
makes things work for me.

Please add this correction.

**Comment by dannybloe** [comment]
Ah, are you able to make a pull request for this? I'm kind busy with lot's of other stuff lately. Let me know if you can't and I'll see if I fit it in at some point.

**Comment by MarcusKlerks** [comment]
I think I succeeded (first time for everything...)
