### ISSUE TITLE
SwitchOff().for_min working ?

### ISSUE THREAD

**Issue by Merangle** [dannybloe/dzVents#29]
Hello

I've tried 
domoticz.devices['H '..Piece].switchOn().for_min(Duree)
If duree = 2, the witch turns on and then turns off after 2 min

The same 
domoticz.devices['H '..Piece].switchOff().for_min(Duree)
If duree = 2, the witch turns off and then DOESN'T turns on after 2 min

Any idea why ?
Thanks

**Comment by dannybloe** [comment]
I cannot reproduce this one. I tried it in my setup and this works. In my logs I see this command being sent 

`[1] = Raamlicht: Off FOR 1`

when I do this:

```
if (device.state == 'On') then
	domoticz.devices['Foo'].switchOff().for_min(1)
end
```

And than after a minute I see this:
```

2016-10-17 21:24:15.257 OpenZWave: Domoticz has send a Switch command! NodeID: 8 (0x08)
2016-10-17 21:24:15.746 (Razberry) Light/Switch (Foo)

```

**Comment by dannybloe** [comment]
No response.. Closing for now. 
Let me know if it is still a problem.
