### ISSUE TITLE
dzvents scritps not working after 3 weeks

### ISSUE THREAD

**Issue by guiguid** [dannybloe/dzVents#36]
zdvents works perfectly form weeks, but now it dosen't ...

>  2016-11-27 07:42:34.015 LUA: /home/pi/domoticz/scripts/lua/dzVents/EventHelpers.lua:262: attempt to index local 'pfile' (a nil value)
> 2016-11-27 07:42:34.017 Error: EventSystem: in /home/pi/domoticz/scripts/lua/script_device_main.lua: /home/pi/domoticz/scripts/lua/dzVents/EventHelpers.lua:608: bad argument #1 to 'pairs' (table expected, got nil) 

restarting domoticz solved the issue ...

**Comment by dannybloe** [comment]
Great.. closing
