### ISSUE TITLE
dzVents doesn't work in latest beta

### ISSUE THREAD

**Issue by adrianmihalko** [dannybloe/dzVents#37]
I updated to latest beta but my dzVent script is stopped working. I checked log in Domoticz and I see:

` Error: EventSystem: in /home/madrian/domoticz/scripts/lua/script_time_main.lua: /home/madrian/domoticz/scripts/lua/dzVents/EventHelpers.lua:78: attempt to index local 'fileStorage' (a boolean value)`

**Comment by dannybloe** [comment]
It is possible there is something wrong with one of your __data_xxx.lua files (inside scripts/lua/scripts/storage folder). Could you try to remove these files or inspect them? They hold the persistent data for you scripts.

**Comment by adrianmihalko** [comment]
I deleted the files in the storage folder and now it works. Thank you.
