### ISSUE TITLE
Script logging level (Request for enhancement)

### ISSUE THREAD

**Issue by allan-gam** [dannybloe/dzVents#43]
The dzVents default logging level can be set in dzVents_settings.lua. ``['Log level'] = 1``. By doing that, log events with lower priority (e.g. higher numbers) won't show up in the log. However there are moments when you'd like to override the default dzVents logging level per script basis to make output more verbose.  That would be especially useful when developing a new script.

Another idea is to add the ability to add a unique number or text to a dzVents script that will show up in all log messages. By doing that, one can set a filter while watching the Domoticz log, seeing only the log messages that are of interest for the moment. I currently add something similar to this to all my dzVents scripts:
``local logPre = 'alarm'``. When I want to log something I do: ``domoticz.log(logPre..'Set lightingmood to \'Movie\'', domoticz.LOG_DEBUG) `` When prepending each log entry with a text like that, it can be good to use the scripts file name (without the .lua extension) so that lua script errors also will be seen while filtering the log.

**Comment by dannybloe** [comment]
In the domoticz integration branch I added the option to define a logging section in your script:

```
return {
    ....
    logging = {
        level = domoticz.LOG_INFO,
        marker = 'My marker' -- marker is prefixed to the log message
    },
    ....
}
```
