### ISSUE TITLE
Interact with all switches and sensors using JSON with an optional delay argument

### ISSUE THREAD

**Issue by allan-gam** [dannybloe/dzVents#44]
Wouldn't it be nice to incorporate the following into Domoticz.lua ?

Some devices like the RGBW device seems to work best if controlled by API/Json URL commands. The small function below would help doing those commands and it also allows a delay (seconds).

```lua
   -- Interact with all switches and sensors using JSON with an optional delay argument
   function self.jsonAPI(apiCall, delay)
      delay = delay or 0
      local url = 'http://'..self.settings['Domoticz ip']..':'..self.settings['Domoticz port']..'/json.htm?'
      if delay == 0 then
         self.sendCommand('OpenURL', url..apiCall)
      else
         os.execute('(sleep '..delay..';curl -s "'..url..apiCall..'" > /dev/null)&')
      end
   end
```

**Comment by dannybloe** [comment]
I don't want to rely on OS specifics actually. I guess the effort should be to figure out why you need json calls for this in the first place. Perhaps post a ticket in the dz tracker?
