### ISSUE TITLE
.for_min() cannot be called successively

### ISSUE THREAD

**Issue by kknuut** [dannybloe/dzVents#45]
If  switchOn().for_min() is called again before last duration has been ended, it seems to keep light on forever. At least longer than what has been accumulated by successive for_min calls.

Expected behavior would be to respect the last time the  .for_min() was called..?

This is a problem with for eg. motion sensor event keeping the light on for xx minutes.  If there is more motion during the light on time, the switch off moment should just be moved forward.   I know this can be done via persistent data etc.. but it's less elegant.

**Comment by dannybloe** [comment]
Unfortunately this is a Domoticz issue that cannot be solved from the lua events.
