### ISSUE TITLE
switchOn for RGBW device not supported?

### ISSUE THREAD

**Issue by OliverHi** [dannybloe/dzVents#51]
Hi, I recently updates my dzVents to version 2 (meaning I deleted my old custom installation and am now using the one integrated in domoticz).
I had a script running that turns on a RGBW device (based on MySensors) with the old installation and ported it to version 2.

Relevant code:

`if (sensor.state == 'On') then -- TODO nighttime +/- some hours?
                sensor.switchOff().afterSec(40)

                if (domoticz.time.isNightTime) then
                    domoticz.devices('RGBW 1').switchOn()
                    domoticz.devices('RGBW 1').switchOff().afterSec(300)
                end

I get an error message every time the code runs telling me that switchOn is not supported:
`Error: Method switchOn is not available for device "RGBW 1" (deviceType=Lighting Limitless/Applamp, deviceSubType=RGBW). If you believe this is not correct, please report.`

You should be able to use the switch methods on a lamp though in my opinion. Or is there another method for that?

**Comment by dannybloe** [comment]
Yes, I already have an adapter update ready for merge as soon as the performance fix is merged into Domoticz. In the meantime you can open the file `path/to/domoticz/scripts/dzVents/runtime/devie-adapters/hue_light_device.lua` and change line 10 into: 
```
local res = (device.deviceType == 'Lighting 2' or device.deviceType == 'Lighting Limitless/Applamp')
```

**Comment by OliverHi** [comment]
Thank you, thats working!
