### ISSUE TITLE
a way to create NEW user variables

### ISSUE THREAD

**Issue by psy0rz** [dannybloe/dzVents#52]
I'm writing an application that uses rfid tags to do stuff. when a tag is unknown i want it to create a uservariables with the name rfid_123 (for example)

then the user can adjust the name of the person and the rol of this tag via the uservars page.

however there is no way to create new uservars from a script.

currently i'm doing some ugly hack like:

commandArray['OpenURL']='http://localhost/json.htm?type=command&param=saveuservariable&vname='..uservar_key..'&vtype=2&vvalue=unnamed:unknown'

is there a way you could add this feature?

**Comment by dannybloe** [comment]
Well, guess that's exactly how I would implement this if I'd add it to dzVents.
But in your case I'd create a helper function addVariable() and use that in your code. I'm not sure yet we should implement all the create APIs from domoticz into dzVents.

**Comment by psy0rz** [comment]
since dzVents is part of the core, cant you just expose some lowlevel api, so that we dont need these json calls? seems kind of hackish this way.

would be nice if we could just do domoticz.variables(key).set(value) on a nonexisting varable, and let domoticz create it.

and perhaps have domoticz.variables(key).exists() or something?

**Comment by dannybloe** [comment]
well, dzVents is kinda stand-alone as it uses the same old commandArray to tell domoticz to do things. Until domoticz accepts these commands from the commandArray dzVents would be forced to use the json API.

**Comment by psy0rz** [comment]
ok thanks
