### ISSUE TITLE
Sleep / Wait

### ISSUE THREAD

**Issue by Condorello** [dannybloe/dzVents#54]
Hello, it's possible to add a "delay" such a "sleep" or a "wait" in a script?
For example could be usefull to do this:

if (device.state == on)   <-- check the actual state when trigger event is triggered
wait 10 minutes
    if (device.state == on )  then <-- i check again if still be on
set it off.

**Comment by dannybloe** [comment]
That cannot be done in a script. A script only responds to events coming from Domoticz. So the only thing you can do is create timer based scripts and check the state and perhaps use lastUpdate information of some sorts.

(Btw, please use the Domoticz forum)
