### ISSUE TITLE
Attribute WActual does not work for MySensors Energy meter

### ISSUE THREAD

**Issue by lrybak** [dannybloe/dzVents#7]
Hi Danny,

I found that for MySensors Energy meter obtaining current Watt usage (WActual) attribute gives a following error:
2016-04-27 09:43:00.673 LUA: x.lua:y: attempt to concatenate field 'WActual' (a nil value)

I've just dumped rawData table from MySensor Energy meter device using inspect module and it seems that only two values exists in rawData table
rawData: { "377.000", "281558.000" }  - first elem is current Watt Usage, second total Wh usage

Hovewer all required data (current W usage, today Wh usage, total Wh usage) exists in device json object - see screenshot

After checking source code I found also that WhToday attribute returns current Watt usage instead of Wh today

if (device.deviceType ==  'General' and device.deviceSubType == 'kWh') then
        device.addAttribute('WhTotal', tonumber(device.rawData[2]))
        device.addAttribute('WhToday', tonumber(device.rawData[1]))
end

Could you please investigate?

If you need more information please let me know

![device](https://cloud.githubusercontent.com/assets/5631648/14846862/28daf1a6-0c66-11e6-845a-5e4deb00e00f.png)

**Comment by dannybloe** [comment]
Good find.. I'll look into it today.

**Comment by dannybloe** [comment]
Bummer, Domoticz doesn't provide the today's value in raw format. I think I have made a fix but it may not work in all cases. In the http data there is only a formatted number (with language specific separators). Please give it a try (in the dev branch!)

**Comment by dannybloe** [comment]
I think this is fixed in the upcoming release (domoticz integration). Closing this for now and let me know when it is out in the open if it still occurs.
