### ISSUE TITLE
domoticz.logDevice sometimes fails

### ISSUE THREAD

**Issue by MarcusKlerks** [dannybloe/dzVents#9]
Using logDevice gave me an error when a attribute value was a Boolean. Looking in to the source code I found line 257 in Domoticz.lua: 
  print(level .. attr .. ': ' .. value) 
to be changed into 
  print(level .. attr .. ': ' .. tostring(value))
solved the problem

**Comment by dannybloe** [comment]
Check! ... and  .. fixed. Check the dev branch. Thanks for spotting.
logDevice may still give you problems as Domoticz tends to choke on too many log messages.
Let me know if it works. Then I'll close the ticket.

**Comment by MarcusKlerks** [comment]
Confirmed to work. Till now I didn't see any problems with logDevice, keep my fingers crossed ;)

**Comment by dannybloe** [comment]
Great.. closing
